/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnternehmenRouteImport } from './routes/unternehmen'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as TerminBestaetigtRouteImport } from './routes/termin-bestaetigt'
import { Route as ProzessRouteImport } from './routes/prozess'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as BewerberRouteImport } from './routes/bewerber'
import { Route as AnalyseTerminRouteImport } from './routes/analyse-termin'
import { Route as AnalyseRouteImport } from './routes/analyse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUnternehmenRouteImport } from './routes/admin.unternehmen'
import { Route as AdminTermineRouteImport } from './routes/admin.termine'
import { Route as AdminSystemstatusRouteImport } from './routes/admin.systemstatus'
import { Route as AdminPipelineRouteImport } from './routes/admin.pipeline'
import { Route as AdminNachrichtenRouteImport } from './routes/admin.nachrichten'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminEinstellungenRouteImport } from './routes/admin.einstellungen'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminBewerberRouteImport } from './routes/admin.bewerber'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as ApiCalendlyWebhookRouteImport } from './routes/api.calendly.webhook'
import { Route as AdminLeadsNewRouteImport } from './routes/admin.leads.new'
import { Route as AdminLeadsIdEditRouteImport } from './routes/admin.leads.$id.edit'

const UnternehmenRoute = UnternehmenRouteImport.update({
  id: '/unternehmen',
  path: '/unternehmen',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminBestaetigtRoute = TerminBestaetigtRouteImport.update({
  id: '/termin-bestaetigt',
  path: '/termin-bestaetigt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProzessRoute = ProzessRouteImport.update({
  id: '/prozess',
  path: '/prozess',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const BewerberRoute = BewerberRouteImport.update({
  id: '/bewerber',
  path: '/bewerber',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyseTerminRoute = AnalyseTerminRouteImport.update({
  id: '/analyse-termin',
  path: '/analyse-termin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyseRoute = AnalyseRouteImport.update({
  id: '/analyse',
  path: '/analyse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUnternehmenRoute = AdminUnternehmenRouteImport.update({
  id: '/admin/unternehmen',
  path: '/admin/unternehmen',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTermineRoute = AdminTermineRouteImport.update({
  id: '/admin/termine',
  path: '/admin/termine',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemstatusRoute = AdminSystemstatusRouteImport.update({
  id: '/admin/systemstatus',
  path: '/admin/systemstatus',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPipelineRoute = AdminPipelineRouteImport.update({
  id: '/admin/pipeline',
  path: '/admin/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNachrichtenRoute = AdminNachrichtenRouteImport.update({
  id: '/admin/nachrichten',
  path: '/admin/nachrichten',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEinstellungenRoute = AdminEinstellungenRouteImport.update({
  id: '/admin/einstellungen',
  path: '/admin/einstellungen',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBewerberRoute = AdminBewerberRouteImport.update({
  id: '/admin/bewerber',
  path: '/admin/bewerber',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendlyWebhookRoute = ApiCalendlyWebhookRouteImport.update({
  id: '/api/calendly/webhook',
  path: '/api/calendly/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsNewRoute = AdminLeadsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminLeadsRoute,
} as any)
const AdminLeadsIdEditRoute = AdminLeadsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminLeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyse': typeof AnalyseRoute
  '/analyse-termin': typeof AnalyseTerminRoute
  '/bewerber': typeof BewerberRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/prozess': typeof ProzessRoute
  '/termin-bestaetigt': typeof TerminBestaetigtRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/unternehmen': typeof UnternehmenRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bewerber': typeof AdminBewerberRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/einstellungen': typeof AdminEinstellungenRoute
  '/admin/leads': typeof AdminLeadsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/nachrichten': typeof AdminNachrichtenRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/systemstatus': typeof AdminSystemstatusRoute
  '/admin/termine': typeof AdminTermineRoute
  '/admin/unternehmen': typeof AdminUnternehmenRoute
  '/admin/leads/new': typeof AdminLeadsNewRoute
  '/api/calendly/webhook': typeof ApiCalendlyWebhookRoute
  '/admin/leads/$id/edit': typeof AdminLeadsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyse': typeof AnalyseRoute
  '/analyse-termin': typeof AnalyseTerminRoute
  '/bewerber': typeof BewerberRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/prozess': typeof ProzessRoute
  '/termin-bestaetigt': typeof TerminBestaetigtRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/unternehmen': typeof UnternehmenRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bewerber': typeof AdminBewerberRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/einstellungen': typeof AdminEinstellungenRoute
  '/admin/leads': typeof AdminLeadsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/nachrichten': typeof AdminNachrichtenRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/systemstatus': typeof AdminSystemstatusRoute
  '/admin/termine': typeof AdminTermineRoute
  '/admin/unternehmen': typeof AdminUnternehmenRoute
  '/admin/leads/new': typeof AdminLeadsNewRoute
  '/api/calendly/webhook': typeof ApiCalendlyWebhookRoute
  '/admin/leads/$id/edit': typeof AdminLeadsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyse': typeof AnalyseRoute
  '/analyse-termin': typeof AnalyseTerminRoute
  '/bewerber': typeof BewerberRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/prozess': typeof ProzessRoute
  '/termin-bestaetigt': typeof TerminBestaetigtRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/unternehmen': typeof UnternehmenRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bewerber': typeof AdminBewerberRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/einstellungen': typeof AdminEinstellungenRoute
  '/admin/leads': typeof AdminLeadsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/nachrichten': typeof AdminNachrichtenRoute
  '/admin/pipeline': typeof AdminPipelineRoute
  '/admin/systemstatus': typeof AdminSystemstatusRoute
  '/admin/termine': typeof AdminTermineRoute
  '/admin/unternehmen': typeof AdminUnternehmenRoute
  '/admin/leads/new': typeof AdminLeadsNewRoute
  '/api/calendly/webhook': typeof ApiCalendlyWebhookRoute
  '/admin/leads/$id/edit': typeof AdminLeadsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyse'
    | '/analyse-termin'
    | '/bewerber'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/prozess'
    | '/termin-bestaetigt'
    | '/ueber-uns'
    | '/unternehmen'
    | '/admin/analytics'
    | '/admin/bewerber'
    | '/admin/dashboard'
    | '/admin/einstellungen'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/nachrichten'
    | '/admin/pipeline'
    | '/admin/systemstatus'
    | '/admin/termine'
    | '/admin/unternehmen'
    | '/admin/leads/new'
    | '/api/calendly/webhook'
    | '/admin/leads/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyse'
    | '/analyse-termin'
    | '/bewerber'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/prozess'
    | '/termin-bestaetigt'
    | '/ueber-uns'
    | '/unternehmen'
    | '/admin/analytics'
    | '/admin/bewerber'
    | '/admin/dashboard'
    | '/admin/einstellungen'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/nachrichten'
    | '/admin/pipeline'
    | '/admin/systemstatus'
    | '/admin/termine'
    | '/admin/unternehmen'
    | '/admin/leads/new'
    | '/api/calendly/webhook'
    | '/admin/leads/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/analyse'
    | '/analyse-termin'
    | '/bewerber'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/prozess'
    | '/termin-bestaetigt'
    | '/ueber-uns'
    | '/unternehmen'
    | '/admin/analytics'
    | '/admin/bewerber'
    | '/admin/dashboard'
    | '/admin/einstellungen'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/nachrichten'
    | '/admin/pipeline'
    | '/admin/systemstatus'
    | '/admin/termine'
    | '/admin/unternehmen'
    | '/admin/leads/new'
    | '/api/calendly/webhook'
    | '/admin/leads/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyseRoute: typeof AnalyseRoute
  AnalyseTerminRoute: typeof AnalyseTerminRoute
  BewerberRoute: typeof BewerberRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  ProzessRoute: typeof ProzessRoute
  TerminBestaetigtRoute: typeof TerminBestaetigtRoute
  UeberUnsRoute: typeof UeberUnsRoute
  UnternehmenRoute: typeof UnternehmenRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBewerberRoute: typeof AdminBewerberRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEinstellungenRoute: typeof AdminEinstellungenRoute
  AdminLeadsRoute: typeof AdminLeadsRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNachrichtenRoute: typeof AdminNachrichtenRoute
  AdminPipelineRoute: typeof AdminPipelineRoute
  AdminSystemstatusRoute: typeof AdminSystemstatusRoute
  AdminTermineRoute: typeof AdminTermineRoute
  AdminUnternehmenRoute: typeof AdminUnternehmenRoute
  ApiCalendlyWebhookRoute: typeof ApiCalendlyWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unternehmen': {
      id: '/unternehmen'
      path: '/unternehmen'
      fullPath: '/unternehmen'
      preLoaderRoute: typeof UnternehmenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termin-bestaetigt': {
      id: '/termin-bestaetigt'
      path: '/termin-bestaetigt'
      fullPath: '/termin-bestaetigt'
      preLoaderRoute: typeof TerminBestaetigtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prozess': {
      id: '/prozess'
      path: '/prozess'
      fullPath: '/prozess'
      preLoaderRoute: typeof ProzessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bewerber': {
      id: '/bewerber'
      path: '/bewerber'
      fullPath: '/bewerber'
      preLoaderRoute: typeof BewerberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyse-termin': {
      id: '/analyse-termin'
      path: '/analyse-termin'
      fullPath: '/analyse-termin'
      preLoaderRoute: typeof AnalyseTerminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyse': {
      id: '/analyse'
      path: '/analyse'
      fullPath: '/analyse'
      preLoaderRoute: typeof AnalyseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/unternehmen': {
      id: '/admin/unternehmen'
      path: '/admin/unternehmen'
      fullPath: '/admin/unternehmen'
      preLoaderRoute: typeof AdminUnternehmenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/termine': {
      id: '/admin/termine'
      path: '/admin/termine'
      fullPath: '/admin/termine'
      preLoaderRoute: typeof AdminTermineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/systemstatus': {
      id: '/admin/systemstatus'
      path: '/admin/systemstatus'
      fullPath: '/admin/systemstatus'
      preLoaderRoute: typeof AdminSystemstatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pipeline': {
      id: '/admin/pipeline'
      path: '/admin/pipeline'
      fullPath: '/admin/pipeline'
      preLoaderRoute: typeof AdminPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/nachrichten': {
      id: '/admin/nachrichten'
      path: '/admin/nachrichten'
      fullPath: '/admin/nachrichten'
      preLoaderRoute: typeof AdminNachrichtenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/einstellungen': {
      id: '/admin/einstellungen'
      path: '/admin/einstellungen'
      fullPath: '/admin/einstellungen'
      preLoaderRoute: typeof AdminEinstellungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bewerber': {
      id: '/admin/bewerber'
      path: '/admin/bewerber'
      fullPath: '/admin/bewerber'
      preLoaderRoute: typeof AdminBewerberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendly/webhook': {
      id: '/api/calendly/webhook'
      path: '/api/calendly/webhook'
      fullPath: '/api/calendly/webhook'
      preLoaderRoute: typeof ApiCalendlyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads/new': {
      id: '/admin/leads/new'
      path: '/new'
      fullPath: '/admin/leads/new'
      preLoaderRoute: typeof AdminLeadsNewRouteImport
      parentRoute: typeof AdminLeadsRoute
    }
    '/admin/leads/$id/edit': {
      id: '/admin/leads/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/leads/$id/edit'
      preLoaderRoute: typeof AdminLeadsIdEditRouteImport
      parentRoute: typeof AdminLeadsRoute
    }
  }
}

interface AdminLeadsRouteChildren {
  AdminLeadsNewRoute: typeof AdminLeadsNewRoute
  AdminLeadsIdEditRoute: typeof AdminLeadsIdEditRoute
}

const AdminLeadsRouteChildren: AdminLeadsRouteChildren = {
  AdminLeadsNewRoute: AdminLeadsNewRoute,
  AdminLeadsIdEditRoute: AdminLeadsIdEditRoute,
}

const AdminLeadsRouteWithChildren = AdminLeadsRoute._addFileChildren(
  AdminLeadsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyseRoute: AnalyseRoute,
  AnalyseTerminRoute: AnalyseTerminRoute,
  BewerberRoute: BewerberRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  ProzessRoute: ProzessRoute,
  TerminBestaetigtRoute: TerminBestaetigtRoute,
  UeberUnsRoute: UeberUnsRoute,
  UnternehmenRoute: UnternehmenRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBewerberRoute: AdminBewerberRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEinstellungenRoute: AdminEinstellungenRoute,
  AdminLeadsRoute: AdminLeadsRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminNachrichtenRoute: AdminNachrichtenRoute,
  AdminPipelineRoute: AdminPipelineRoute,
  AdminSystemstatusRoute: AdminSystemstatusRoute,
  AdminTermineRoute: AdminTermineRoute,
  AdminUnternehmenRoute: AdminUnternehmenRoute,
  ApiCalendlyWebhookRoute: ApiCalendlyWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
